/*
 * API - Contas a Receber
 * Esta API faz parte do processo de recebimento de lote o REST com ASP.NET Core WebAPI.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.3.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/api/v1/Level/GetByPeriodId", () => {
        let periodId = 'TODO_EDIT_THE_PERIODID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Level/GetByPeriodId?periodId=${periodId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Management/Responsible", () => {
        let name = 'TODO_EDIT_THE_NAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Management/Responsible?name=${name}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Billets/Responsible/{Id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let datePayment = 'TODO_EDIT_THE_DATEPAYMENT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetId = 'TODO_EDIT_THE_BILLETID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Billets/Responsible/${Id}?datePayment=${datePayment}&billetId=${billetId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/UpdateStatus", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/UpdateStatus`;
            // TODO: edit the parameters of the request body.
            let body = {"id": "uuid", "status": "integer"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Management/Responsibles/Contracts", () => {
        let endDate = 'TODO_EDIT_THE_ENDDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let selectpersonIds = 'TODO_EDIT_THE_SELECTPERSONIDS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let initialDate = 'TODO_EDIT_THE_INITIALDATE'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Management/Responsibles/Contracts?selectpersonIds=${selectpersonIds}&initialDate=${initialDate}&endDate=${endDate}&limit=${limit}&skip=${skip}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/LegalEntity/{username}", () => {
        let username = 'TODO_EDIT_THE_USERNAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/LegalEntity/${username}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/CashierManagement", () => {
        let cashierManagementStatus = 'TODO_EDIT_THE_CASHIERMANAGEMENTSTATUS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let entityDescription = 'TODO_EDIT_THE_ENTITYDESCRIPTION'; // specify value as there is no example value for this parameter in OpenAPI spec
        let itemsPage = 'TODO_EDIT_THE_ITEMSPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dateOpenStart = 'TODO_EDIT_THE_DATEOPENSTART'; // specify value as there is no example value for this parameter in OpenAPI spec
        let userName = 'TODO_EDIT_THE_USERNAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let currentPage = 'TODO_EDIT_THE_CURRENTPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dateOpenFinal = 'TODO_EDIT_THE_DATEOPENFINAL'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/CashierManagement?dateOpenStart=${dateOpenStart}&dateOpenFinal=${dateOpenFinal}&userName=${userName}&entityDescription=${entityDescription}&cashierManagementStatus=${cashierManagementStatus}&currentPage=${currentPage}&itemsPage=${itemsPage}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/DueDateInBatches/GetDueDaysByLegalEntity", () => {
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/DueDateInBatches/GetDueDaysByLegalEntity?legalEntityId=${legalEntityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/ExportReceivingLines/{ReceivingBatchId}", () => {
        let receivingBatchId = 'TODO_EDIT_THE_RECEIVINGBATCHID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/ExportReceivingLines/${ReceivingBatchId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/CashierManagement/TransferBatchToCashier", () => {
        let cashierId = 'TODO_EDIT_THE_CASHIERID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let batchId = 'TODO_EDIT_THE_BATCHID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/CashierManagement/TransferBatchToCashier?batchId=${batchId}&cashierId=${cashierId}`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Currentaccounts", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Currentaccounts`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/v1/Currentaccounts`;
            // TODO: edit the parameters of the request body.
            let body = {"currentAccountId": "uuid", "date": "date", "contractId": "uuid", "serviceId": "uuid", "accountsReceivableTypeId": "uuid", "value": "double", "levelId": "uuid", "observation": "string", "journalId": "uuid", "transactionAfsId": "uuid", "toAccount": "boolean", "cancelled": "boolean", "username": "string", "generatedDate": "date"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/BankRemittance/Status", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/BankRemittance/Status`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/RecurringCard/Filter", () => {
        let nameBeneficiary = 'TODO_EDIT_THE_NAMEBENEFICIARY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let digitCard = 'TODO_EDIT_THE_DIGITCARD'; // specify value as there is no example value for this parameter in OpenAPI spec
        let year = 'TODO_EDIT_THE_YEAR'; // specify value as there is no example value for this parameter in OpenAPI spec
        let name = 'TODO_EDIT_THE_NAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let currentPage = 'TODO_EDIT_THE_CURRENTPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let totalItemByPage = 'TODO_EDIT_THE_TOTALITEMBYPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let status = 'TODO_EDIT_THE_STATUS'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/RecurringCard/Filter?totalItemByPage=${totalItemByPage}&currentPage=${currentPage}&name=${name}&nameBeneficiary=${nameBeneficiary}&digitCard=${digitCard}&year=${year}&entityId=${entityId}&status=${status}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/{id}/DeleteBatch", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/${id}/DeleteBatch`;
            let request = http.del(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/CountStatus", () => {
        let billetValue = 'TODO_EDIT_THE_BILLETVALUE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let receivingBatch = 'TODO_EDIT_THE_RECEIVINGBATCH'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetDueDate = 'TODO_EDIT_THE_BILLETDUEDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetNumber = 'TODO_EDIT_THE_BILLETNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/CountStatus?receivingBatch=${receivingBatch}&billetNumber=${billetNumber}&billetDueDate=${billetDueDate}&statusReturn=${statusReturn}&billetValue=${billetValue}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Journal/GetAccountingMonth", () => {
        let month = 'TODO_EDIT_THE_MONTH'; // specify value as there is no example value for this parameter in OpenAPI spec
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let year = 'TODO_EDIT_THE_YEAR'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Journal/GetAccountingMonth?legalEntityId=${legalEntityId}&month=${month}&year=${year}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Manage/Bug/GenerateProcess", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Manage/Bug/GenerateProcess`;
            // TODO: edit the parameters of the request body.
            let body = {"financialAgreementId": "string", "lines": "list"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.put(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/DueDateInBatches", () => {
        let periodId = 'TODO_EDIT_THE_PERIODID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let itemsPage = 'TODO_EDIT_THE_ITEMSPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dueDateStart = 'TODO_EDIT_THE_DUEDATESTART'; // specify value as there is no example value for this parameter in OpenAPI spec
        let serviceId = 'TODO_EDIT_THE_SERVICEID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let currentPage = 'TODO_EDIT_THE_CURRENTPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dueDateFinal = 'TODO_EDIT_THE_DUEDATEFINAL'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/DueDateInBatches?periodId=${periodId}&dueDateStart=${dueDateStart}&dueDateFinal=${dueDateFinal}&serviceId=${serviceId}&currentPage=${currentPage}&itemsPage=${itemsPage}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/Count", () => {
        let status = 'TODO_EDIT_THE_STATUS'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/Count?status=${status}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Login", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Login`;
            // TODO: edit the parameters of the request body.
            let body = {"entityId": "uuid", "countryId": "integer", "entityDescription": "string", "legalEntityId": "uuid", "systemId": "uuid", "systemName": "string"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Journal/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Journal/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/CashierManagement/GetCashiersToTransferByEntityId", () => {
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/CashierManagement/GetCashiersToTransferByEntityId?entityId=${entityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/MappingCurrentAccountBillet/GetByContractId", () => {
        let contractId = 'TODO_EDIT_THE_CONTRACTID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/MappingCurrentAccountBillet/GetByContractId?contractId=${contractId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/{id}/Account", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/${id}/Account`;
            // TODO: edit the parameters of the request body.
            let body = {"dateSelected": "string"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/SaleOff", () => {
        let billetValue = 'TODO_EDIT_THE_BILLETVALUE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let type = 'TODO_EDIT_THE_TYPE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetDueDate = 'TODO_EDIT_THE_BILLETDUEDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetNumber = 'TODO_EDIT_THE_BILLETNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/SaleOff?id=${id}&type=${type}&skip=${skip}&limit=${limit}&billetDueDate=${billetDueDate}&billetNumber=${billetNumber}&statusReturn=${statusReturn}&billetValue=${billetValue}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Entity/GetEntityPermission/{username}", () => {
        let username = 'TODO_EDIT_THE_USERNAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Entity/GetEntityPermission/${username}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Level/GetLevelByEntityId", () => {
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Level/GetLevelByEntityId?entityId=${entityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Journal/{id}/Itens", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Journal/${id}/Itens`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Management/Contract/{id}/Round", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Management/Contract/${id}/Round`;
            let request = http.patch(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/SchedulingTask/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/SchedulingTask/${id}`;
            // TODO: edit the parameters of the request body.
            let body = {"id": "uuid", "startTime": "integer", "waitingHours": "integer", "lastRun": "date", "taskType": {"name": "string", "id": "integer"}, "isActive": "boolean"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.put(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Entity/GetPeriodByEntity/{entityId}", () => {
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Entity/GetPeriodByEntity/${entityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/FacturationPy/GetFacturationPy", () => {
        let levelId = 'TODO_EDIT_THE_LEVELID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let subAccount = 'TODO_EDIT_THE_SUBACCOUNT'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/FacturationPy/GetFacturationPy?subAccount=${subAccount}&entityId=${entityId}&levelId=${levelId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/UpdateLineStatusSetBatch", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/UpdateLineStatusSetBatch`;
            // TODO: edit the parameters of the request body.
            let body = {"linesId": "list", "batchId": "uuid"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/RecurringCard/GetRecurringInstallmentsOnCard", () => {
        let periodId = 'TODO_EDIT_THE_PERIODID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusRecurrenceId = 'TODO_EDIT_THE_STATUSRECURRENCEID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let nameResponsibleOrBeneficiary = 'TODO_EDIT_THE_NAMERESPONSIBLEORBENEFICIARY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let endDate = 'TODO_EDIT_THE_ENDDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let digitCard = 'TODO_EDIT_THE_DIGITCARD'; // specify value as there is no example value for this parameter in OpenAPI spec
        let beneficiaryName = 'TODO_EDIT_THE_BENEFICIARYNAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let totalItemsByPage = 'TODO_EDIT_THE_TOTALITEMSBYPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let currentPage = 'TODO_EDIT_THE_CURRENTPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let startDate = 'TODO_EDIT_THE_STARTDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetNumber = 'TODO_EDIT_THE_BILLETNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/RecurringCard/GetRecurringInstallmentsOnCard?LegalEntityId=${LegalEntityId}&PeriodId=${PeriodId}&StartDate=${StartDate}&EndDate=${EndDate}&NameResponsibleOrBeneficiary=${NameResponsibleOrBeneficiary}&CurrentPage=${CurrentPage}&TotalItemsByPage=${TotalItemsByPage}&EntityId=${EntityId}&StatusRecurrenceId=${StatusRecurrenceId}&BeneficiaryName=${BeneficiaryName}&DigitCard=${DigitCard}&BilletNumber=${BilletNumber}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/SchedulingTask/Types", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/SchedulingTask/Types`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/BankReturnFile", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/BankReturnFile`;
            // TODO: edit the parameters of the request body.
            let body = {"file": http.file(open("/path/to/file.bin", "b"), "test.bin")};
            let params = {headers: {"Content-Type": "multipart/form-data", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/CashierManagement/FinancialAccount", () => {
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/CashierManagement/FinancialAccount?legalEntityId=${legalEntityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Management/AccountingTypeUpdate", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Management/AccountingTypeUpdate`;
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/DueDateInBatches/GetPeriodsByLegalEntity", () => {
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/DueDateInBatches/GetPeriodsByLegalEntity?legalEntityId=${legalEntityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/CountRecordedCharge", () => {
        let receivingBatch = 'TODO_EDIT_THE_RECEIVINGBATCH'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/CountRecordedCharge?receivingBatch=${receivingBatch}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Systemtesting/Logged", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Systemtesting/Logged`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Management/Person/{id}/Contracts", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Management/Person/${id}/Contracts`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/ProcessAllLinesBatch", () => {
        let lineStatus = 'TODO_EDIT_THE_LINESTATUS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/ProcessAllLinesBatch?id=${id}&lineStatus=${lineStatus}&statusReturn=${statusReturn}`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/ProcessLinesFromBatchByStatus", () => {
        let lineStatus = 'TODO_EDIT_THE_LINESTATUS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dateIni = 'TODO_EDIT_THE_DATEINI'; // specify value as there is no example value for this parameter in OpenAPI spec
        let processStatus = 'TODO_EDIT_THE_PROCESSSTATUS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dateFim = 'TODO_EDIT_THE_DATEFIM'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/ProcessLinesFromBatchByStatus?processStatus=${processStatus}&lineStatus=${lineStatus}&statusReturn=${statusReturn}&dateIni=${dateIni}&dateFim=${dateFim}`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/RecurringCard/GetAllStatusRecurrence", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/RecurringCard/GetAllStatusRecurrence`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/RecurringCard", () => {
        let year = 'TODO_EDIT_THE_YEAR'; // specify value as there is no example value for this parameter in OpenAPI spec
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let responsibleId = 'TODO_EDIT_THE_RESPONSIBLEID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let responsibleName = 'TODO_EDIT_THE_RESPONSIBLENAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/RecurringCard?responsibleId=${responsibleId}&responsibleName=${responsibleName}&year=${year}&legalEntityId=${legalEntityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/v1/RecurringCard`;
            // TODO: edit the parameters of the request body.
            let body = {"responsibleId": "uuid", "creditCard": {"customerName": "string", "cardNumber": "string", "holder": "string", "expirationDate": "string", "brand": "string"}, "contracts": "list"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Remittance/Batch", () => {
        let fileName = 'TODO_EDIT_THE_FILENAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let generateDate = 'TODO_EDIT_THE_GENERATEDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let financialAgreementId = 'TODO_EDIT_THE_FINANCIALAGREEMENTID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Remittance/Batch?skip=${skip}&limit=${limit}&fileName=${fileName}&financialAgreementId=${financialAgreementId}&generateDate=${generateDate}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Entity/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Entity/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/DueDateInBatches/AlterDueDateInBatch", () => {
        let periodId = 'TODO_EDIT_THE_PERIODID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let allBilletsByFilter = 'TODO_EDIT_THE_ALLBILLETSBYFILTER'; // specify value as there is no example value for this parameter in OpenAPI spec
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dueDateStart = 'TODO_EDIT_THE_DUEDATESTART'; // specify value as there is no example value for this parameter in OpenAPI spec
        let newDueDate = 'TODO_EDIT_THE_NEWDUEDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let accompaniesDiscount = 'TODO_EDIT_THE_ACCOMPANIESDISCOUNT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let serviceId = 'TODO_EDIT_THE_SERVICEID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dueDateFinal = 'TODO_EDIT_THE_DUEDATEFINAL'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/DueDateInBatches/AlterDueDateInBatch?periodId=${periodId}&dueDateStart=${dueDateStart}&newDueDate=${newDueDate}&allBilletsByFilter=${allBilletsByFilter}&accompaniesDiscount=${accompaniesDiscount}&legalEntityId=${legalEntityId}&dueDateFinal=${dueDateFinal}&serviceId=${serviceId}`;
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Journal/{id}/Export", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Journal/${id}/Export`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Remittance/Batch/{id}/Download", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Remittance/Batch/${id}/Download`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/MappingCurrentAccountBillet/GetContractsByParam", () => {
        let periodId = 'TODO_EDIT_THE_PERIODID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let levelId = 'TODO_EDIT_THE_LEVELID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let mappingFilterEnum = 'TODO_EDIT_THE_MAPPINGFILTERENUM'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/MappingCurrentAccountBillet/GetContractsByParam?levelId=${levelId}&periodId=${periodId}&MappingFilterEnum=${MappingFilterEnum}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/SchedulingTask", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/SchedulingTask`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/v1/SchedulingTask?taskType=${taskType}`;
            let request = http.head(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/ProcessFile", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/ProcessFile`;
            // TODO: edit the parameters of the request body.
            let body = {"typeProcess": "integer", "processLines": "list", "batchId": "uuid"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/InternationalPayment", () => {
        let paymentValue = 'TODO_EDIT_THE_PAYMENTVALUE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let paymentDate = 'TODO_EDIT_THE_PAYMENTDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetId = 'TODO_EDIT_THE_BILLETID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/InternationalPayment?paymentValue=${paymentValue}&billetId=${billetId}&paymentDate=${paymentDate}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/GetBatchByFile", () => {
        let fileName = 'TODO_EDIT_THE_FILENAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/GetBatchByFile?fileName=${fileName}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Remittance/Batch/{id}/Lines", () => {
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Remittance/Batch/${id}/Lines?skip=${skip}&limit=${limit}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/CashierManagement/DepositCash", () => {
        let batchId = 'TODO_EDIT_THE_BATCHID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/CashierManagement/DepositCash?batchId=${batchId}`;
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/MappingCurrentAccountBillet/ReMappingList", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/MappingCurrentAccountBillet/ReMappingList`;
            // TODO: edit the parameters of the request body.
            let body = {"contractIds": "list"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Entity/GetEntityIdByLegalEntityId/{legalEntityId}", () => {
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Entity/GetEntityIdByLegalEntityId/${legalEntityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/GetLinesFromBatchId", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/GetLinesFromBatchId?id=${id}&statusReturn=${statusReturn}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Person", () => {
        let personName = 'TODO_EDIT_THE_PERSONNAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Person?personName=${personName}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Entity/GetEntityChildByEntityId/{entityId}", () => {
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Entity/GetEntityChildByEntityId/${entityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/Batch/{Id}/{Limit}/RegisteredChargeProcessAll", () => {
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/Batch/${Id}/${Limit}/RegisteredChargeProcessAll`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Contract/GetByParams", () => {
        let periodId = 'TODO_EDIT_THE_PERIODID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let levelId = 'TODO_EDIT_THE_LEVELID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Contract/GetByParams?levelId=${levelId}&periodId=${periodId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/JournalType/GetAll", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/JournalType/GetAll`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/RecurringCard/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/RecurringCard/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/v1/RecurringCard/${id}`;
            let request = http.del(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/{id}/Lines/Count", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/${id}/Lines/Count`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Services/ServiceGroup", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Services/ServiceGroup`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Level/GetByEntityIdAndSubAccount", () => {
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let subAccount = 'TODO_EDIT_THE_SUBACCOUNT'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Level/GetByEntityIdAndSubAccount?entityId=${entityId}&subAccount=${subAccount}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/FinancialAgreements", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/FinancialAgreements`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/ProcessAllLineStatus", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/ProcessAllLineStatus`;
            // TODO: edit the parameters of the request body.
            let body = {"linesId": "list", "statusId": "integer"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/SaveChangeLine", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/SaveChangeLine`;
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Manage/Bug/Itens", () => {
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let financialAgreementId = 'TODO_EDIT_THE_FINANCIALAGREEMENTID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Manage/Bug/Itens?financialAgreementId=${financialAgreementId}&limit=${limit}&skip=${skip}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/RecordedCharge", () => {
        let billetValue = 'TODO_EDIT_THE_BILLETVALUE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturnLine = 'TODO_EDIT_THE_STATUSRETURNLINE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetDueDate = 'TODO_EDIT_THE_BILLETDUEDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetNumber = 'TODO_EDIT_THE_BILLETNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/RecordedCharge?id=${id}&skip=${skip}&limit=${limit}&billetDueDate=${billetDueDate}&billetNumber=${billetNumber}&statusReturn=${statusReturn}&statusReturnLine=${statusReturnLine}&billetValue=${billetValue}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/CashierManagement/CanTransferBatch", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/CashierManagement/CanTransferBatch`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Currentaccounts/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Currentaccounts/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/v1/Currentaccounts/${id}`;
            let request = http.del(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Journal/{id}/Item/Update", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Journal/${id}/Item/Update`;
            // TODO: edit the parameters of the request body.
            let body = {"description": "string", "value": "double", "accountCode": "string", "subAccount": "string", "departmentCode": "string", "fundCode": "string", "restrictionCode": "string", "sortOrder": "integer", "isSuccess": "boolean", "errorDescription": "string", "source": "string", "journalItemIds": "list"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.put(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/GetLinesFromBatchStatus", () => {
        let dateIni = 'TODO_EDIT_THE_DATEINI'; // specify value as there is no example value for this parameter in OpenAPI spec
        let lineStatus = 'TODO_EDIT_THE_LINESTATUS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let processStatus = 'TODO_EDIT_THE_PROCESSSTATUS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let dateFim = 'TODO_EDIT_THE_DATEFIM'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/GetLinesFromBatchStatus?processStatus=${processStatus}&dateIni=${dateIni}&dateFim=${dateFim}&lineStatus=${lineStatus}&statusReturn=${statusReturn}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/ToManage", () => {
        let fileName = 'TODO_EDIT_THE_FILENAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let endDate = 'TODO_EDIT_THE_ENDDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let initialDate = 'TODO_EDIT_THE_INITIALDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let status = 'TODO_EDIT_THE_STATUS'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/ToManage?skip=${skip}&status=${status}&limit=${limit}&fileName=${fileName}&initialDate=${initialDate}&endDate=${endDate}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/RecurringCard/Flags", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/RecurringCard/Flags`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/RecurringCard/GetRecurringInstallmentsTotalValue", () => {
        let periodId = 'TODO_EDIT_THE_PERIODID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusRecurrenceId = 'TODO_EDIT_THE_STATUSRECURRENCEID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let nameResponsibleOrBeneficiary = 'TODO_EDIT_THE_NAMERESPONSIBLEORBENEFICIARY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let endDate = 'TODO_EDIT_THE_ENDDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let digitCard = 'TODO_EDIT_THE_DIGITCARD'; // specify value as there is no example value for this parameter in OpenAPI spec
        let beneficiaryName = 'TODO_EDIT_THE_BENEFICIARYNAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let totalItemsByPage = 'TODO_EDIT_THE_TOTALITEMSBYPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let currentPage = 'TODO_EDIT_THE_CURRENTPAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let startDate = 'TODO_EDIT_THE_STARTDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetNumber = 'TODO_EDIT_THE_BILLETNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/RecurringCard/GetRecurringInstallmentsTotalValue?LegalEntityId=${LegalEntityId}&PeriodId=${PeriodId}&StartDate=${StartDate}&EndDate=${EndDate}&NameResponsibleOrBeneficiary=${NameResponsibleOrBeneficiary}&CurrentPage=${CurrentPage}&TotalItemsByPage=${TotalItemsByPage}&EntityId=${EntityId}&StatusRecurrenceId=${StatusRecurrenceId}&BeneficiaryName=${BeneficiaryName}&DigitCard=${DigitCard}&BilletNumber=${BilletNumber}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Batch/{id}/Lines", () => {
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Batch/${id}/Lines?skip=${skip}&limit=${limit}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/SchedulingTask/{id}/Run", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/SchedulingTask/${id}/Run`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Period/GetByEntityIdAndSubAccount", () => {
        let entityId = 'TODO_EDIT_THE_ENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let subAccount = 'TODO_EDIT_THE_SUBACCOUNT'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Period/GetByEntityIdAndSubAccount?entityId=${entityId}&subAccount=${subAccount}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Journal", () => {
        let number = 'TODO_EDIT_THE_NUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec
        let month = 'TODO_EDIT_THE_MONTH'; // specify value as there is no example value for this parameter in OpenAPI spec
        let endDate = 'TODO_EDIT_THE_ENDDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let year = 'TODO_EDIT_THE_YEAR'; // specify value as there is no example value for this parameter in OpenAPI spec
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let page = 'TODO_EDIT_THE_PAGE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let journalTypeId = 'TODO_EDIT_THE_JOURNALTYPEID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let batchTypeId = 'TODO_EDIT_THE_BATCHTYPEID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let userName = 'TODO_EDIT_THE_USERNAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let initialDate = 'TODO_EDIT_THE_INITIALDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let status = 'TODO_EDIT_THE_STATUS'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Journal?journalTypeId=${journalTypeId}&batchTypeId=${batchTypeId}&page=${page}&limit=${limit}&userName=${userName}&initialDate=${initialDate}&endDate=${endDate}&month=${month}&year=${year}&status=${status}&number=${number}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/BankRemittance/File/Generate", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/BankRemittance/File/Generate`;
            // TODO: edit the parameters of the request body.
            let body = {"batch": {"financialAgreement": "financialagreementvm"}, "lines": "list"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/MappingCurrentAccountBillet/ReMapping", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/MappingCurrentAccountBillet/ReMapping`;
            // TODO: edit the parameters of the request body.
            let body = {"contractId": "uuid"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/BankRemittance/Itens", () => {
        let endDate = 'TODO_EDIT_THE_ENDDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let beneficiaryName = 'TODO_EDIT_THE_BENEFICIARYNAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let agreementId = 'TODO_EDIT_THE_AGREEMENTID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let limit = 'TODO_EDIT_THE_LIMIT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let ourNumber = 'TODO_EDIT_THE_OURNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec
        let responsibleName = 'TODO_EDIT_THE_RESPONSIBLENAME'; // specify value as there is no example value for this parameter in OpenAPI spec
        let initialDate = 'TODO_EDIT_THE_INITIALDATE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let status = 'TODO_EDIT_THE_STATUS'; // specify value as there is no example value for this parameter in OpenAPI spec
        let billetNumber = 'TODO_EDIT_THE_BILLETNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/BankRemittance/Itens?agreementId=${agreementId}&initialDate=${initialDate}&endDate=${endDate}&status=${status}&billetNumber=${billetNumber}&ourNumber=${ourNumber}&beneficiaryName=${beneficiaryName}&responsibleName=${responsibleName}&limit=${limit}&skip=${skip}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/DueDateInBatches/GetServicesByLegalEntity", () => {
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/DueDateInBatches/GetServicesByLegalEntity?legalEntityId=${legalEntityId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/ProcessLinesByLineStatus", () => {
        let lineStatusTo = 'TODO_EDIT_THE_LINESTATUSTO'; // specify value as there is no example value for this parameter in OpenAPI spec
        let lineStatusFrom = 'TODO_EDIT_THE_LINESTATUSFROM'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/ProcessLinesByLineStatus?id=${id}&lineStatusFrom=${lineStatusFrom}&lineStatusTo=${lineStatusTo}&statusReturn=${statusReturn}`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/InternationalPayment/{billetId}", () => {
        let billetId = 'TODO_EDIT_THE_BILLETID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/InternationalPayment/${billetId}`;
            let request = http.del(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/GetLinesFromBatchIdByStatus", () => {
        let statusLine = 'TODO_EDIT_THE_STATUSLINE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let batchId = 'TODO_EDIT_THE_BATCHID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let statusReturn = 'TODO_EDIT_THE_STATUSRETURN'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/GetLinesFromBatchIdByStatus?batchId=${batchId}&statusReturn=${statusReturn}&statusLine=${statusLine}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/Batch/{Id}/ProcessAll", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/Batch/${Id}/ProcessAll`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Management/Person", () => {
        let name = 'TODO_EDIT_THE_NAME'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Management/Person?name=${name}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Journal/Status", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Journal/Status`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/_hubs", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/_hubs`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/v1/_hubs?userName=${userName}`;
            let request = http.post(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Receiving/Lines/Report", () => {
        let batchId = 'TODO_EDIT_THE_BATCHID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Receiving/Lines/Report?batchId=${batchId}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/Systemtesting/Problem", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/Systemtesting/Problem`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/AccountingJournal/GetAccountingJournalByFiltersRoute", () => {
        let legalEntityId = 'TODO_EDIT_THE_LEGALENTITYID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let journalType = 'TODO_EDIT_THE_JOURNALTYPE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let printOption = 'TODO_EDIT_THE_PRINTOPTION'; // specify value as there is no example value for this parameter in OpenAPI spec
        let toExport = 'TODO_EDIT_THE_TOEXPORT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let accountingMonthId = 'TODO_EDIT_THE_ACCOUNTINGMONTHID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let journalId = 'TODO_EDIT_THE_JOURNALID'; // specify value as there is no example value for this parameter in OpenAPI spec
        let serviceCodeGroup = 'TODO_EDIT_THE_SERVICECODEGROUP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let legalEntityGroup = 'TODO_EDIT_THE_LEGALENTITYGROUP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let accountsReceivingTypeGroup = 'TODO_EDIT_THE_ACCOUNTSRECEIVINGTYPEGROUP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let accountingLotNumber = 'TODO_EDIT_THE_ACCOUNTINGLOTNUMBER'; // specify value as there is no example value for this parameter in OpenAPI spec
        let accountingLot = 'TODO_EDIT_THE_ACCOUNTINGLOT'; // specify value as there is no example value for this parameter in OpenAPI spec
        let periodGroup = 'TODO_EDIT_THE_PERIODGROUP'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/v1/AccountingJournal/GetAccountingJournalByFiltersRoute?journalId=${journalId}&accountingMonthId=${accountingMonthId}&legalEntityId=${legalEntityId}&journalType=${journalType}&printOption=${printOption}&legalEntityGroup=${legalEntityGroup}&periodGroup=${periodGroup}&accountsReceivingTypeGroup=${accountsReceivingTypeGroup}&serviceCodeGroup=${serviceCodeGroup}&toExport=${toExport}&accountingLotNumber=${accountingLotNumber}&accountingLot=${accountingLot}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
            check(request, {
                "No Content": (r) => r.status === 204
            });
        }
    });

}
